# Generated by Django 5.2.3 on 2025-06-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='img',
            field=models.URLField(default='https://www.livelaw.in/h-upload/2022/07/04/750x450_424441-restaurant.jpg'),
        ),
    ]
